version: '3'
services:
  proxy:
    image: registry.openanalytics.eu/proxy/library/nginx:alpine
    restart: unless-stopped
    container_name: oa-rdepot-proxy
    labels:
      eu.openanalytics.rdepot.container.name: 'oa-rdepot-proxy'
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/rdepot.conf:/etc/nginx/sites-enabled/rdepot:ro
      - repository:/opt/rdepot/repo/:ro
      - logs:/var/log/nginx/
    depends_on:
      - backend
      - repo
      - frontend
      - keycloak
    ports:
      - 8017:80
    networks:
      oa-rdepot:
        aliases:
          - oa-rdepot-proxy
  backend:
    image: registry.openanalytics.eu/openanalytics/rdepot-app:2.1.0-SNAPSHOT
    restart: unless-stopped
    hostname: oa-rdepot-backend
    container_name: oa-rdepot-backend
    volumes:
      - ./docker/backend/application-test.yml:/opt/rdepot/application.yml
      - repositories:/opt/rdepot/repositories/
      - snapshots:/opt/rdepot/generated/
      - queue:/opt/rdepot/new/
    ports:
      - 8080:8080
    depends_on:
      - db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -f http://localhost:8080/backend/actuator/health -H 'Accept: application/json' || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/rdepot
      - DB_USERNAME=rdepot
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.11
        aliases:
          - oa-rdepot-backend
  db:
    image: registry.openanalytics.eu/proxy/library/postgres:alpine
    labels:
      eu.openanalytics.rdepot.container.name: 'oa-rdepot-db'
    restart: unless-stopped
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=rdepot
      - POSTGRES_USER=rdepot
    networks:
      oa-rdepot:
        aliases:
          - oa-rdepot-db
  repo:
    image: registry.openanalytics.eu/openanalytics/rdepot-repo:2.1.0-SNAPSHOT
    restart: unless-stopped
    container_name: oa-rdepot-repo
    labels:
      eu.openanalytics.rdepot.container.name: 'oa-rdepot-repo'
    hostname: oa-rdepot-repo
    volumes:
      - repository:/opt/rdepot/
    networks:
      oa-rdepot:
        aliases:
          - oa-rdepot-repo
  frontend:
    container_name: oa-rdepot-frontend
    hostname: oa-rdepot-frontend
    build:
      context: .
    restart: unless-stopped
    labels:
      eu.openanalytics.rdepot.container.name: 'oa-rdepot-frontend'
    ports:
      - 3001:80
    networks:
      oa-rdepot:
        ipv4_address: 192.168.49.13
        aliases:
          - oa-rdepot-frontend
    environment:
      - VITE_LOGIN_SIMPLE=true
      - VITE_LOGIN_OIDC=false
      - VITE_URL_PREFIX=/
      - VITE_SERVER_ADDRESS=http://172.17.0.1:8080/backend
      - VITE_OIDC_AUTHORITY=http://localhost/keycloak/realms/RDepot
      - VITE_OIDC_CLIENT_ID=oa-rdepot-frontend
      - VITE_OIDC_REDIRECT_URI=http://localhost/auth
      - VITE_OIDC_POST_LOGOUT_REDIRECT_URI=http://localhost/logout
      - VITE_OIDC_RESPONSE_TYPE=code
      - VITE_OIDC_SCOPE=openid
  selenium:
    image: registry.openanalytics.eu/proxy/selenium/standalone-chrome:125.0
    restart: unless-stopped
    hostname: oa-rdepot-selenium
    container_name: oa-rdepot-selenium
    ports:
      - 4444:4444
    networks:
      - oa-rdepot
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.49.0/24
volumes:
  repository:
  repositories:
  snapshots:
  queue:
  logs:
