version: '3'
services:
  proxy:
    image: registry.openanalytics.eu/proxy/library/nginx:bookworm
    restart: unless-stopped
    container_name: oa-rdepot-proxy-firefox
    labels:
      eu.openanalytics.rdepot.container.name: 'oa-rdepot-proxy-firefox'
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/rdepot-test.conf:/etc/nginx/sites-enabled/rdepot:ro
      - repository:/opt/rdepot/repo/:ro
    depends_on:
      - backend
      - repo
      - frontend
    # ports:
    #   - 8018:80
    networks:
      oa-rdepot:
        ipv4_address: 192.168.51.20
        aliases:
          - oa-rdepot-proxy
  backend:
    image: registry.openanalytics.eu/openanalytics/rdepot-app:2.6.0-SNAPSHOT
    restart: unless-stopped
    hostname: oa-rdepot-backend
    container_name: oa-rdepot-backend-firefox
    volumes:
      - ./docker/backend/application-test-firefox.yml:/opt/rdepot/application.yml
      - repositories:/opt/rdepot/repositories/
      - snapshots:/opt/rdepot/generated/
      - queue:/opt/rdepot/new/
      - ./docker/testData/itestSourceFiles:/opt/testSourceFiles:ro
      - ./docker/testData/itestGenerated:/opt/testGenerated:ro
      - ./docker/testData/itestNewFiles:/opt/newFiles:ro
      - ./docker/testData/itestTrashFiles:/opt/trashFiles:ro
    # ports:
    # - 8080:8080
    depends_on:
      - db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -f http://localhost:8080/backend/actuator/health -H 'Accept: application/json' || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/rdepot
      - DB_USERNAME=rdepot
    networks:
      oa-rdepot:
        ipv4_address: 192.168.51.11
        aliases:
          - oa-rdepot-backend-firefox
  db:
    image: registry.openanalytics.eu/proxy/library/postgres:alpine
    labels:
      eu.openanalytics.rdepot.container.name: 'oa-rdepot-db-firefox'
    restart: unless-stopped
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db-firefox
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=rdepot
      - POSTGRES_USER=rdepot
    volumes:
      - ./docker/db/initial_scripts/:/docker-entrypoint-initdb.d/:ro
      - ./docker/db/sql_files/:/opt/sql_files/:ro
    networks:
      oa-rdepot:
        aliases:
          - oa-rdepot-db-firefox
  repo:
    image: registry.openanalytics.eu/openanalytics/rdepot-repo:2.6.0-SNAPSHOT
    restart: unless-stopped
    container_name: oa-rdepot-repo-firefox
    labels:
      eu.openanalytics.rdepot.container.name: 'oa-rdepot-repo-firefox'
    hostname: oa-rdepot-repo
    volumes:
      - repository:/opt/rdepot/
    networks:
      oa-rdepot:
        aliases:
          - oa-rdepot-repo-firefox
  frontend:
    container_name: oa-rdepot-frontend-firefox
    hostname: oa-rdepot-frontend
    build:
      context: .
    restart: unless-stopped
    labels:
      eu.openanalytics.rdepot.container.name: 'oa-rdepot-frontend-firefox'
    ports:
      - 3002:8080
    networks:
      oa-rdepot:
        ipv4_address: 192.168.51.13
        aliases:
          - oa-rdepot-frontend-firefox
    environment:
      - VITE_LOGIN_SIMPLE=true
      - VITE_LOGIN_OIDC=false
      - VITE_URL_PREFIX=/
      - VITE_SERVER_ADDRESS=http://192.168.51.20/backend
      - VITE_ADDRESS_DEPRECATION_WARNING=true
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.51.0/24
volumes:
  repository:
  repositories:
  snapshots:
  queue:
