#!/bin/sh
JSON_STRING='window.configs = { \
  "VITE_LOGIN_OIDC":"'"${VITE_LOGIN_OIDC}"'", \
  "VITE_LOGIN_SIMPLE":"'"${VITE_LOGIN_SIMPLE}"'", \
  "VITE_OIDC_AUTHORITY":"'"${VITE_OIDC_AUTHORITY}"'", \
  "VITE_OIDC_CLIENT_ID":"'"${VITE_OIDC_CLIENT_ID}"'", \
  "VITE_OIDC_REDIRECT_URI":"'"${VITE_OIDC_REDIRECT_URI}"'", \
  "VITE_OIDC_POST_LOGOUT_REDIRECT_URI":"'"${VITE_OIDC_POST_LOGOUT_REDIRECT_URI}"'", \
  "VITE_OIDC_RESPONSE_TYPE":"'"${VITE_OIDC_RESPONSE_TYPE}"'", \
  "VITE_OIDC_SCOPE":"'"${VITE_OIDC_SCOPE}"'", \
  "VITE_ADDRESS_DEPRECATION_WARNING":"'"${VITE_ADDRESS_DEPRECATION_WARNING}"'", \
  "VITE_DEV_MODE":"'"${VITE_DEV_MODE}"'", \
  "VITE_URL_PREFIX":"'"${VITE_URL_PREFIX}"'", \
  "VITE_SERVER_ADDRESS":"'"${VITE_SERVER_ADDRESS}"'", \
  "VITE_CURRENT_COMMIT_VERSION":"'"${VITE_CURRENT_COMMIT_VERSION}"'", \
  "VITE_ALLOWED_PACKAGE_DESCRIPTION_TAGS":"'"${VITE_ALLOWED_PACKAGE_DESCRIPTION_TAGS}"'", \
  "VITE_NAVBAR_TITLE":"'"${VITE_NAVBAR_TITLE}"'", \
  "VITE_DARK_MODE_BACKGROUND_COLOUR":"'"${VITE_DARK_MODE_BACKGROUND_COLOUR}"'", \
  "VITE_LIGHT_MODE_BACKGROUND_COLOUR":"'"${VITE_LIGHT_MODE_BACKGROUND_COLOUR}"'", \
  "VITE_PRIMARY_COLOUR":"'"${VITE_PRIMARY_COLOUR}"'", \
  "VITE_LOGO_SMALL_URL":"'"${VITE_LOGO_SMALL_URL}"'", \
  "VITE_LOGO_SMALL_HEIGHT":"'"${VITE_LOGO_SMALL_HEIGHT}"'", \
  "VITE_LOGO_SMALL_WIDTH":"'"${VITE_LOGO_SMALL_WIDTH}"'", \
  "VITE_LOGO_SMALL_CLASSES":"'"${VITE_LOGO_SMALL_CLASSES}"'", \
  "VITE_LOGO_SMALL_STYLE":"'"${VITE_LOGO_SMALL_STYLE}"'", \
  "VITE_LOGO_BIG_URL":"'"${VITE_LOGO_BIG_URL}"'", \
  "VITE_LOGO_BIG_HEIGHT":"'"${VITE_LOGO_BIG_HEIGHT}"'", \
  "VITE_LOGO_BIG_WIDTH":"'"${VITE_LOGO_BIG_WIDTH}"'", \
  "VITE_LOGO_BIG_CLASSES":"'"${VITE_LOGO_BIG_CLASSES}"'", \
  "VITE_LOGO_BIG_STYLE":"'"${VITE_LOGO_BIG_STYLE}"'", \
}'
sed -i "s@// CONFIGURATIONS_PLACEHOLDER@${JSON_STRING}@" /usr/share/nginx/html/index.html
exec "$@"
