apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rdepot-client-build
    docker: kaniko-rdepot-client
spec:
  volumes:
    - name: dockerconfig
      secret:
        secretName: oa-sa-jenkins-registry-config
  containers:
    - name: rdepot-client-build
      image: registry.openanalytics.eu/openanalytics/rdepot-client-build:latest
      resources:
        limits:
          memory: "4Gi"
          ephemeral-storage: "4Gi"
          cpu: 2
        requests:
          memory: "2Gi"
          ephemeral-storage: "1Gi"
          cpu: 1
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockerconfig
          mountPath: /.docker/config.json
          subPath: data
      env:
        - name: COMPOSE_HTTP_TIMEOUT
          value: 600
      imagePullPolicy: Always
    - name: jnlp
      resources:
        requests:
            memory: "2Gi"
            ephemeral-storage: "1Gi"
            cpu: 1
        limits:
            memory: "4Gi"
            ephemeral-storage: "4Gi"
            cpu: 2
