apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: rdepot-client-build
spec:
  imagePullSecrets:
  - name: registry-robot
  containers:
  - name: rdepot-client-build
    image: registry.openanalytics.eu/proxy/library/node:lts-alpine
    resources:
      limits:
        memory: '4Gi'
        ephemeral-storage: '4Gi'
        cpu: 2
      requests:
        memory: '2Gi'
        ephemeral-storage: '1Gi'
        cpu: 1
    tty: true
    securityContext:
      privileged: true
    env:
    - name: COMPOSE_HTTP_TIMEOUT
      value: 600
    imagePullPolicy: Always
