/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CollectionModelRoleDtoEmbedded } from './collection-model-role-dto-embedded'
import { Links } from './links'
/**
 *
 *
 * @export
 * @interface CollectionModelRoleDto
 */
export interface CollectionModelRoleDto {
  /**
   * @type {CollectionModelRoleDtoEmbedded}
   * @memberof CollectionModelRoleDto
   */
  embedded?: CollectionModelRoleDtoEmbedded

  /**
   * @type {Links}
   * @memberof CollectionModelRoleDto
   */
  links?: Links
}
