/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Link } from './link'
import { UserSettingsProjection } from './user-settings-projection'
/**
 *
 * @export
 * @interface EntityModelUserDto
 */
export interface EntityModelUserDto {
  /**
   *
   * @type {number}
   * @memberof EntityModelUserDto
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof EntityModelUserDto
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof EntityModelUserDto
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof EntityModelUserDto
   */
  login?: string
  /**
   *
   * @type {boolean}
   * @memberof EntityModelUserDto
   */
  active?: boolean
  /**
   *
   * @type {string}
   * @memberof EntityModelUserDto
   */
  lastLoggedInOn?: string
  /**
   *
   * @type {string}
   * @memberof EntityModelUserDto
   */
  createdOn?: string
  /**
   *
   * @type {boolean}
   * @memberof EntityModelUserDto
   */
  deleted?: boolean
  /**
   *
   * @type {number}
   * @memberof EntityModelUserDto
   */
  roleId?: number
  /**
   *
   * @type {string}
   * @memberof EntityModelUserDto
   */
  role?: string
  /**
   *
   * @type {UserSettingsProjection}
   * @memberof EntityModelUserDto
   */
  userSettings?: UserSettingsProjection
  /**
   *
   * @type {string}
   * @memberof EntityModelUserDto
   */
  description?: string
  /**
   *
   * @type {Array<Link>}
   * @memberof EntityModelUserDto
   */
  links?: Array<Link>
}
