/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Links } from './links'
import { UserProjection } from './user-projection'
/**
 *
 *
 * @export
 * @interface EntityModelAccessTokenDto
 */
export interface EntityModelAccessTokenDto {
  /**
   * @type {number}
   * @memberof EntityModelAccessTokenDto
   */
  id?: number

  /**
   * @type {string}
   * @memberof EntityModelAccessTokenDto
   */
  name?: string

  /**
   * @type {string}
   * @memberof EntityModelAccessTokenDto
   */
  value?: string

  /**
   * @type {string}
   * @memberof EntityModelAccessTokenDto
   */
  creationDate?: string

  /**
   * @type {string}
   * @memberof EntityModelAccessTokenDto
   */
  expirationDate?: string

  /**
   * @type {boolean}
   * @memberof EntityModelAccessTokenDto
   */
  active?: boolean

  /**
   * @type {boolean}
   * @memberof EntityModelAccessTokenDto
   */
  deleted?: boolean

  /**
   * @type {UserProjection}
   * @memberof EntityModelAccessTokenDto
   */
  user?: UserProjection

  /**
   * @type {string}
   * @memberof EntityModelAccessTokenDto
   */
  lastUsed?: string

  /**
   * @type {Links}
   * @memberof EntityModelAccessTokenDto
   */
  links?: Links
}
