/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Link } from './link';
/**
 * 
 * @export
 * @interface EntityModelPackageDtoObjectObject
 */
export interface EntityModelPackageDtoObjectObject {
    /**
     * 
     * @type {number}
     * @memberof EntityModelPackageDtoObjectObject
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelPackageDtoObjectObject
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityModelPackageDtoObjectObject
     */
    version?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityModelPackageDtoObjectObject
     */
    repositoryId?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelPackageDtoObjectObject
     */
    submissionId?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityModelPackageDtoObjectObject
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelPackageDtoObjectObject
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelPackageDtoObjectObject
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelPackageDtoObjectObject
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelPackageDtoObjectObject
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelPackageDtoObjectObject
     */
    source?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelPackageDtoObjectObject
     */
    active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelPackageDtoObjectObject
     */
    deleted?: boolean;
    /**
     * 
     * @type {Array<Link>}
     * @memberof EntityModelPackageDtoObjectObject
     */
    links?: Array<Link>;
}
