/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Links } from './links'
/**
 *
 *
 * @export
 * @interface EntityModelRRepositoryDto
 */
export interface EntityModelRRepositoryDto {
  /**
   * @type {number}
   * @memberof EntityModelRRepositoryDto
   */
  id?: number

  /**
   * @type {number}
   * @memberof EntityModelRRepositoryDto
   */
  version?: number

  /**
   * @type {string}
   * @memberof EntityModelRRepositoryDto
   */
  publicationUri?: string

  /**
   * @type {string}
   * @memberof EntityModelRRepositoryDto
   */
  name?: string

  /**
   * @type {string}
   * @memberof EntityModelRRepositoryDto
   */
  serverAddress?: string

  /**
   * @type {boolean}
   * @memberof EntityModelRRepositoryDto
   */
  deleted?: boolean

  /**
   * @type {boolean}
   * @memberof EntityModelRRepositoryDto
   */
  published?: boolean

  /**
   * @type {boolean}
   * @memberof EntityModelRRepositoryDto
   */
  synchronizing?: boolean

  /**
   * @type {string}
   * @memberof EntityModelRRepositoryDto
   */
  technology?: string

  /**
   * @type {boolean}
   * @memberof EntityModelRRepositoryDto
   */
  requiresAuthentication?: boolean

  /**
   * @type {number}
   * @memberof EntityModelRRepositoryDto
   */
  numberOfPackages?: number

  /**
   * @type {string}
   * @memberof EntityModelRRepositoryDto
   */
  lastPublicationTimestamp?: string

  /**
   * @type {string}
   * @memberof EntityModelRRepositoryDto
   */
  lastModifiedTimestamp?: string

  /**
   * @type {boolean}
   * @memberof EntityModelRRepositoryDto
   */
  lastPublicationSuccessful?: boolean

  /**
   * @type {Links}
   * @memberof EntityModelRRepositoryDto
   */
  links?: Links
}
