/*
 * R Depot
 *
 * Copyright (C) 2012-2024 Open Analytics NV
 *
 * ===========================================================================
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Apache License as published by
 * The Apache Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Apache License for more details.
 *
 * You should have received a copy of the Apache License
 * along with this program. If not, see <http://www.apache.org/licenses/>
 *
 */

import { EntityModelPackageDto } from './entity-model-package-dto'
import { EntityModelRepositoryDto } from './entity-model-repository-dto'
import { EntityModelUserDto } from './entity-model-user-dto'

/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface IDto
 */
export interface IDto {
  /**
   * @type {String}
   * @memberof IDto
   */
  name?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  creationDate?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  expirationDate?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  version?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  technology?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  packageName?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  role?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  login?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  email?: String

  /**
   * @type {String}
   * @memberof IDto
   */
  state?: String

  /**
   * @type {EntityModelRepositoryDto}
   * @memberof IDto
   */
  repository?: EntityModelRepositoryDto

  /**
   * @type {EntityModelUserDto}
   * @memberof IDto
   */
  user?: EntityModelUserDto

  /**
   * @type {EntityModelPackageDto}
   * @memberof IDto
   */
  packageBag?: EntityModelPackageDto
}
