/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EntityModelAccessTokenDto } from './entity-model-access-token-dto'
/**
 *
 *
 * @export
 * @interface PagedModelEntityModelAccessTokenDtoEmbedded
 */
export interface PagedModelEntityModelAccessTokenDtoEmbedded {
  /**
   * @type {Array<EntityModelAccessTokenDto>}
   * @memberof PagedModelEntityModelAccessTokenDtoEmbedded
   */
  accessTokenDtoList?: Array<EntityModelAccessTokenDto>
}
