/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityModelPackageDto } from './entity-model-package-dto'
import { Link } from './link'
import { PageMetadata } from './page-metadata'
/**
 *
 * @export
 * @interface PagedModelEntityModelPackageDto
 */
export interface PagedModelEntityModelPackageDto {
  /**
   *
   * @type {Array<Link>}
   * @memberof PagedModelEntityModelPackageDto
   */
  links?: Array<Link>
  /**
   *
   * @type {Array<EntityModelPackageDto>}
   * @memberof PagedModelEntityModelPackageDto
   */
  content?: Array<EntityModelPackageDto>
  /**
   *
   * @type {PageMetadata}
   * @memberof PagedModelEntityModelPackageDto
   */
  page?: PageMetadata
}
