/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EntityModelRepositoryMaintainerDto } from './entity-model-repository-maintainer-dto'
/**
 *
 *
 * @export
 * @interface PagedModelEntityModelRepositoryMaintainerDtoEmbedded
 */
export interface PagedModelEntityModelRepositoryMaintainerDtoEmbedded {
  /**
   * @type {Array<EntityModelRepositoryMaintainerDto>}
   * @memberof PagedModelEntityModelRepositoryMaintainerDtoEmbedded
   */
  repositoryMaintainerDtoList?: Array<EntityModelRepositoryMaintainerDto>
}
