/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EntityModelNewsfeedEventDto } from './entity-model-newsfeed-event-dto'
/**
 *
 *
 * @export
 * @interface PagedModelEntityModelNewsfeedEventDtoEmbedded
 */
export interface PagedModelEntityModelNewsfeedEventDtoEmbedded {
  /**
   * @type {Array<EntityModelNewsfeedEventDto>}
   * @memberof PagedModelEntityModelNewsfeedEventDtoEmbedded
   */
  newsfeedEventDtoList?: Array<EntityModelNewsfeedEventDto>
}
