/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityModelRepositoryMaintainerDto } from './entity-model-repository-maintainer-dto';
import { Link } from './link';
import { PageMetadata } from './page-metadata';
/**
 * 
 * @export
 * @interface PagedModelEntityModelRepositoryMaintainerDto
 */
export interface PagedModelEntityModelRepositoryMaintainerDto {
    /**
     * 
     * @type {Array<Link>}
     * @memberof PagedModelEntityModelRepositoryMaintainerDto
     */
    links?: Array<Link>;
    /**
     * 
     * @type {Array<EntityModelRepositoryMaintainerDto>}
     * @memberof PagedModelEntityModelRepositoryMaintainerDto
     */
    content?: Array<EntityModelRepositoryMaintainerDto>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelRepositoryMaintainerDto
     */
    page?: PageMetadata;
}
