/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EntityModelPythonRepositoryDto } from './entity-model-python-repository-dto'
/**
 *
 *
 * @export
 * @interface PagedModelEntityModelPythonRepositoryDtoEmbedded
 */
export interface PagedModelEntityModelPythonRepositoryDtoEmbedded {
  /**
   * @type {Array<EntityModelPythonRepositoryDto>}
   * @memberof PagedModelEntityModelPythonRepositoryDtoEmbedded
   */
  pythonRepositoryDtoList?: Array<EntityModelPythonRepositoryDto>
}
