/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Links } from './links'
import { PageMetadata } from './page-metadata'
import { PagedModelEntityModelPackageMaintainerDtoEmbedded } from './paged-model-entity-model-package-maintainer-dto-embedded'
/**
 *
 *
 * @export
 * @interface PagedModelEntityModelPackageMaintainerDto
 */
export interface PagedModelEntityModelPackageMaintainerDto {
  /**
   * @type {PagedModelEntityModelPackageMaintainerDtoEmbedded}
   * @memberof PagedModelEntityModelPackageMaintainerDto
   */
  embedded?: PagedModelEntityModelPackageMaintainerDtoEmbedded

  /**
   * @type {Links}
   * @memberof PagedModelEntityModelPackageMaintainerDto
   */
  links?: Links

  /**
   * @type {PageMetadata}
   * @memberof PagedModelEntityModelPackageMaintainerDto
   */
  page?: PageMetadata
}
