/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Links } from './links'
import { PageMetadata } from './page-metadata'
import { PagedModelEntityModelAccessTokenDtoEmbedded } from './paged-model-entity-model-access-token-dto-embedded'
/**
 *
 *
 * @export
 * @interface PagedModelEntityModelAccessTokenDto
 */
export interface PagedModelEntityModelAccessTokenDto {
  /**
   * @type {PagedModelEntityModelAccessTokenDtoEmbedded}
   * @memberof PagedModelEntityModelAccessTokenDto
   */
  embedded?: PagedModelEntityModelAccessTokenDtoEmbedded

  /**
   * @type {Links}
   * @memberof PagedModelEntityModelAccessTokenDto
   */
  links?: Links

  /**
   * @type {PageMetadata}
   * @memberof PagedModelEntityModelAccessTokenDto
   */
  page?: PageMetadata
}
