/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityModelRepositoryDto } from './entity-model-repository-dto'
import { Link } from './link'
import { PageMetadata } from './page-metadata'
/**
 *
 * @export
 * @interface PagedModelEntityModelRepositoryDto
 */
export interface PagedModelEntityModelRepositoryDto {
  /**
   *
   * @type {Array<Link>}
   * @memberof PagedModelEntityModelRepositoryDto
   */
  links?: Array<Link>
  /**
   *
   * @type {Array<EntityModelRepositoryDto>}
   * @memberof PagedModelEntityModelRepositoryDto
   */
  content?: Array<EntityModelRepositoryDto>
  /**
   *
   * @type {PageMetadata}
   * @memberof PagedModelEntityModelRepositoryDto
   */
  page?: PageMetadata
}
