/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface PublicConfigurationDto
 */
export interface PublicConfigurationDto {
  /**
   * @type {boolean}
   * @memberof PublicConfigurationDto
   */
  declarativeModeEnabled?: boolean

  /**
   * @type {boolean}
   * @memberof PublicConfigurationDto
   */
  deletingPackagesEnabled?: boolean

  /**
   * @type {boolean}
   * @memberof PublicConfigurationDto
   */
  deletingRepositoriesEnabled?: boolean

  /**
   * @type {boolean}
   * @memberof PublicConfigurationDto
   */
  replacingPackagesEnabled?: boolean

  /**
   * @type {boolean}
   * @memberof PublicConfigurationDto
   */
  accessTokenLifetimeConfigurable?: boolean

  /**
   * @type {number}
   * @memberof PublicConfigurationDto
   */
  accessTokenLifetimeDefault?: number

  /**
   * @type {boolean}
   * @memberof PublicConfigurationDto
   */
  generateManuals?: boolean
}
