/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface RepositoryProjection
 */
export interface RepositoryProjection {
  /**
   * @type {number}
   * @memberof RepositoryProjection
   */
  id?: number

  /**
   * @type {string}
   * @memberof RepositoryProjection
   */
  name?: string

  /**
   * @type {string}
   * @memberof RepositoryProjection
   */
  publicationUri?: string

  /**
   * @type {boolean}
   * @memberof RepositoryProjection
   */
  published?: boolean

  /**
   * @type {boolean}
   * @memberof RepositoryProjection
   */
  requiresAuthentication?: boolean

  /**
   * @type {string}
   * @memberof RepositoryProjection
   */
  technology?: string

  /**
   * @type {boolean}
   * @memberof RepositoryProjection
   */
  lastPublicationSuccessful?: boolean
}
