/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RepositoryMaintainerDto
 */
export interface RepositoryMaintainerDto {
    /**
     * 
     * @type {number}
     * @memberof RepositoryMaintainerDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RepositoryMaintainerDto
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof RepositoryMaintainerDto
     */
    repositoryId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RepositoryMaintainerDto
     */
    deleted?: boolean;
}
