/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PagedModelEntityModelPackageDto } from './paged-model-entity-model-package-dto'
/**
 *
 *
 * @export
 * @interface ResponseDtoPagedModelEntityModelPackageDto
 */
export interface ResponseDtoPagedModelEntityModelPackageDto {
  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelPackageDto
   */
  status?: ResponseDtoPagedModelEntityModelPackageDtoStatusEnum

  /**
   * @type {number}
   * @memberof ResponseDtoPagedModelEntityModelPackageDto
   */
  code?: number

  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelPackageDto
   */
  message?: string

  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelPackageDto
   */
  messageCode?: string

  /**
   * @type {PagedModelEntityModelPackageDto}
   * @memberof ResponseDtoPagedModelEntityModelPackageDto
   */
  data?: PagedModelEntityModelPackageDto
}

/**
 * @export
 * @enum {string}
 */
export enum ResponseDtoPagedModelEntityModelPackageDtoStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  WARNING = 'WARNING'
}
