/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PagedModelEntityModelRepositoryMaintainerDto } from './paged-model-entity-model-repository-maintainer-dto'
/**
 *
 * @export
 * @interface ResponseDtoPagedModelEntityModelRepositoryMaintainerDto
 */
export interface ResponseDtoPagedModelEntityModelRepositoryMaintainerDto {
  /**
   *
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelRepositoryMaintainerDto
   */
  status?: ResponseDtoPagedModelEntityModelRepositoryMaintainerDtoStatusEnum
  /**
   *
   * @type {number}
   * @memberof ResponseDtoPagedModelEntityModelRepositoryMaintainerDto
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelRepositoryMaintainerDto
   */
  message?: string
  /**
   *
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelRepositoryMaintainerDto
   */
  messageCode?: string
  /**
   *
   * @type {PagedModelEntityModelRepositoryMaintainerDto}
   * @memberof ResponseDtoPagedModelEntityModelRepositoryMaintainerDto
   */
  data?: PagedModelEntityModelRepositoryMaintainerDto
}

/**
 * @export
 * @enum {string}
 */
export enum ResponseDtoPagedModelEntityModelRepositoryMaintainerDtoStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
