/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PagedModelEntityModelPackageMaintainerDto } from './paged-model-entity-model-package-maintainer-dto'
/**
 *
 *
 * @export
 * @interface ResponseDtoPagedModelEntityModelPackageMaintainerDto
 */
export interface ResponseDtoPagedModelEntityModelPackageMaintainerDto {
  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelPackageMaintainerDto
   */
  status?: ResponseDtoPagedModelEntityModelPackageMaintainerDtoStatusEnum

  /**
   * @type {number}
   * @memberof ResponseDtoPagedModelEntityModelPackageMaintainerDto
   */
  code?: number

  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelPackageMaintainerDto
   */
  message?: string

  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelPackageMaintainerDto
   */
  messageCode?: string

  /**
   * @type {PagedModelEntityModelPackageMaintainerDto}
   * @memberof ResponseDtoPagedModelEntityModelPackageMaintainerDto
   */
  data?: PagedModelEntityModelPackageMaintainerDto
}

/**
 * @export
 * @enum {string}
 */
export enum ResponseDtoPagedModelEntityModelPackageMaintainerDtoStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  WARNING = 'WARNING'
}
