/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RPublicConfigurationDto } from './rpublic-configuration-dto'
/**
 *
 *
 * @export
 * @interface ResponseDtoRPublicConfigurationDto
 */
export interface ResponseDtoRPublicConfigurationDto {
  /**
   * @type {string}
   * @memberof ResponseDtoRPublicConfigurationDto
   */
  status?: ResponseDtoRPublicConfigurationDtoStatusEnum

  /**
   * @type {number}
   * @memberof ResponseDtoRPublicConfigurationDto
   */
  code?: number

  /**
   * @type {string}
   * @memberof ResponseDtoRPublicConfigurationDto
   */
  message?: string

  /**
   * @type {string}
   * @memberof ResponseDtoRPublicConfigurationDto
   */
  messageCode?: string

  /**
   * @type {RPublicConfigurationDto}
   * @memberof ResponseDtoRPublicConfigurationDto
   */
  data?: RPublicConfigurationDto
}

/**
 * @export
 * @enum {string}
 */
export enum ResponseDtoRPublicConfigurationDtoStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  WARNING = 'WARNING'
}
