/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EntityModelRPackageDto } from './entity-model-rpackage-dto'
/**
 *
 *
 * @export
 * @interface ResponseDtoEntityModelRPackageDto
 */
export interface ResponseDtoEntityModelRPackageDto {
  /**
   * @type {string}
   * @memberof ResponseDtoEntityModelRPackageDto
   */
  status?: ResponseDtoEntityModelRPackageDtoStatusEnum

  /**
   * @type {number}
   * @memberof ResponseDtoEntityModelRPackageDto
   */
  code?: number

  /**
   * @type {string}
   * @memberof ResponseDtoEntityModelRPackageDto
   */
  message?: string

  /**
   * @type {string}
   * @memberof ResponseDtoEntityModelRPackageDto
   */
  messageCode?: string

  /**
   * @type {EntityModelRPackageDto}
   * @memberof ResponseDtoEntityModelRPackageDto
   */
  data?: EntityModelRPackageDto
}

/**
 * @export
 * @enum {string}
 */
export enum ResponseDtoEntityModelRPackageDtoStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  WARNING = 'WARNING'
}
