/* tslint:disable */

/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PagedModelEntityModelRRepositoryDto } from './paged-model-entity-model-rrepository-dto'
/**
 *
 *
 * @export
 * @interface ResponseDtoPagedModelEntityModelRRepositoryDto
 */
export interface ResponseDtoPagedModelEntityModelRRepositoryDto {
  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelRRepositoryDto
   */
  status?: ResponseDtoPagedModelEntityModelRRepositoryDtoStatusEnum

  /**
   * @type {number}
   * @memberof ResponseDtoPagedModelEntityModelRRepositoryDto
   */
  code?: number

  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelRRepositoryDto
   */
  message?: string

  /**
   * @type {string}
   * @memberof ResponseDtoPagedModelEntityModelRRepositoryDto
   */
  messageCode?: string

  /**
   * @type {PagedModelEntityModelRRepositoryDto}
   * @memberof ResponseDtoPagedModelEntityModelRRepositoryDto
   */
  data?: PagedModelEntityModelRRepositoryDto
}

/**
 * @export
 * @enum {string}
 */
export enum ResponseDtoPagedModelEntityModelRRepositoryDtoStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  WARNING = 'WARNING'
}
