/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityModelRepositoryDto } from './entity-model-repository-dto';
/**
 * 
 * @export
 * @interface ResponseDtoEntityModelRepositoryDto
 */
export interface ResponseDtoEntityModelRepositoryDto {
    /**
     * 
     * @type {string}
     * @memberof ResponseDtoEntityModelRepositoryDto
     */
    status?: ResponseDtoEntityModelRepositoryDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ResponseDtoEntityModelRepositoryDto
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseDtoEntityModelRepositoryDto
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseDtoEntityModelRepositoryDto
     */
    messageCode?: string;
    /**
     * 
     * @type {EntityModelRepositoryDto}
     * @memberof ResponseDtoEntityModelRepositoryDto
     */
    data?: EntityModelRepositoryDto;
}

/**
    * @export
    * @enum {string}
    */
export enum ResponseDtoEntityModelRepositoryDtoStatusEnum {
    SUCCESS = 'SUCCESS',
    ERROR = 'ERROR'
}

