/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EntityModelRepositoryMaintainerDto } from './entity-model-repository-maintainer-dto'
/**
 *
 *
 * @export
 * @interface ResponseDtoEntityModelRepositoryMaintainerDto
 */
export interface ResponseDtoEntityModelRepositoryMaintainerDto {
  /**
   * @type {string}
   * @memberof ResponseDtoEntityModelRepositoryMaintainerDto
   */
  status?: ResponseDtoEntityModelRepositoryMaintainerDtoStatusEnum

  /**
   * @type {number}
   * @memberof ResponseDtoEntityModelRepositoryMaintainerDto
   */
  code?: number

  /**
   * @type {string}
   * @memberof ResponseDtoEntityModelRepositoryMaintainerDto
   */
  message?: string

  /**
   * @type {string}
   * @memberof ResponseDtoEntityModelRepositoryMaintainerDto
   */
  messageCode?: string

  /**
   * @type {EntityModelRepositoryMaintainerDto}
   * @memberof ResponseDtoEntityModelRepositoryMaintainerDto
   */
  data?: EntityModelRepositoryMaintainerDto
}

/**
 * @export
 * @enum {string}
 */
export enum ResponseDtoEntityModelRepositoryMaintainerDtoStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  WARNING = 'WARNING'
}
