/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EntityModelPythonPackageDto } from './entity-model-python-package-dto'
/**
 *
 * @export
 * @interface ResponseDtoEntityModelPythonPackageDto
 */
export interface ResponseDtoEntityModelPythonPackageDto {
  /**
   *
   * @type {string}
   * @memberof ResponseDtoEntityModelPythonPackageDto
   */
  status?: ResponseDtoEntityModelPythonPackageDtoStatusEnum
  /**
   *
   * @type {number}
   * @memberof ResponseDtoEntityModelPythonPackageDto
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof ResponseDtoEntityModelPythonPackageDto
   */
  message?: string
  /**
   *
   * @type {string}
   * @memberof ResponseDtoEntityModelPythonPackageDto
   */
  messageCode?: string
  /**
   *
   * @type {EntityModelPythonPackageDto}
   * @memberof ResponseDtoEntityModelPythonPackageDto
   */
  data?: EntityModelPythonPackageDto
}

/**
 * @export
 * @enum {string}
 */
export enum ResponseDtoEntityModelPythonPackageDtoStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
