/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RRepositoryDto
 */
export interface RRepositoryDto {
    /**
     * 
     * @type {number}
     * @memberof RRepositoryDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RRepositoryDto
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof RRepositoryDto
     */
    publicationUri?: string;
    /**
     * 
     * @type {string}
     * @memberof RRepositoryDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RRepositoryDto
     */
    serverAddress?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RRepositoryDto
     */
    deleted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RRepositoryDto
     */
    published?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RRepositoryDto
     */
    synchronizing?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RRepositoryDto
     */
    technology?: string;
}
