/* tslint:disable */
/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UserSettingsProjection
 */
export interface UserSettingsProjection {
  /**
   *
   * @type {string}
   * @memberof UserSettingsProjection
   */
  language?: string
  /**
   *
   * @type {string}
   * @memberof UserSettingsProjection
   */
  theme?: string
  /**
   *
   * @type {number}
   * @memberof UserSettingsProjection
   */
  pageSize?: number
}
