/*
 * R Depot
 *
 * Copyright (C) 2012-2025 Open Analytics NV
 *
 * ===========================================================================
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Apache License as published by
 * The Apache Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Apache License for more details.
 *
 * You should have received a copy of the Apache License
 * along with this program. If not, see <http://www.apache.org/licenses/>
 *
 */

/* eslint-disable */
/**
 * RDEPOT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/api-v2-access-token-controller-api'
export * from './apis/api-v2-config-controller-api'
export * from './apis/api-v2-newsfeed-event-controller-api'
export * from './apis/api-v2-package-controller-api'
export * from './apis/api-v2-package-maintainer-controller-api'
export * from './apis/api-v2-repository-controller-api'
export * from './apis/api-v2-repository-maintainer-controller-api'
export * from './apis/api-v2-status-controller-api'
export * from './apis/api-v2-submission-controller-api'
export * from './apis/api-v2-user-controller-api'
export * from './apis/api-v2-user-settings-controller-api'
export * from './apis/python-package-controller-api'
export * from './apis/python-repository-controller-api'
export * from './apis/python-submission-controller-api'
export * from './apis/rconfig-controller-api'
export * from './apis/rpackage-controller-api'
export * from './apis/rrepository-controller-api'
export * from './apis/rsubmission-controller-api'
